### PR TITLE
Add possibility to configure server directive

### PR DESCRIPTION
**Pull request by EtienneM**
Notify him when merged: https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/15307683558

### CODE REVIEW

**Comment by Soulou** [comment]
Should be tested

**Comment by EtienneM** [comment]
I sure works as it actively used, at least by this customer: https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/conversation/15307683558

**Comment by Soulou** [comment]
Let's merge then

**Comment by Soulou** [comment]
Let's keep the branch as it is used

**Comment by EtienneM** [comment]
@Soulou Do you want me to notify the customer or you handle it?

**Comment by Soulou** [comment]
Please do

**Pull request merged**
